name: custom_lint_core
version: 0.5.7
publish_to: none
description: A package to help writing custom linters
repository: https://github.com/invertase/dart_custom_lint

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analyzer: ">=6.2.0 <7.0.0"
  analyzer_plugin: ^0.11.0
  collection: ^1.17.2
  # Using tight constraints as custom_lint_builder communicate with each-other
  # using a specific contract
  custom_lint:
    git: https://github.com/kumsumit/custom_lint.git
  matcher: ^0.12.0
  meta: ^1.11.0
  path: ^1.8.3
  pubspec_parse: ^1.2.2
  source_span: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.6
  lint_visitor_generator:
    path: ../lint_visitor_generator
  test: ^1.24.9
